# -*- coding: utf-8 -*-
"""exp 7.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaHBZr4waXO8kXTEM9arADhBUVVFQmPr
"""

#question 1

#create a tuple
a=(1, 2,3,4,5,6)
b=(11,12,13,14,15,16)

#concatination operation
c=a+b
print(c)

#length operation
print(len(c))

#repetition operation
print((c)*5)

#memebership operation
print(3 in c)
print(10 in c)


#question 2

t=(10,20,30,40,50)

#indexing operation
print(t[0])

#negative indexing
print(t[-1])


#slicing operation
print(t[1:4])


#iteration operation
print("iterating through tuple:")
for i in t:
  print(i)



  #question no.3


  t=(1,2,3,4)
  #tuples are immutable (cannot change values)
  #uncommenting below line will cause error
  #t[0] = 100

  print(t)

  #deleting tuple
  del t
 #trying to print after deletion will give error
 #print(t)


# question 4

#given sequence (list)
seq=[4,7,9,1,3]

#convert list to tuple
t=tuple(seq)
print(t)

#length
print(len(t))


#maximum value
print(max(t))

#mininum value
print(min(t))