# -*- coding: utf-8 -*-
"""exp 6.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g6FxrfAkKAW0wQR6pv51Gc_o16OLg6Ds
"""

#List
b2=[23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,50]
print(b2)
abs=[45,46,47,48,49]
print(type(b2))


#concatination
b=b2+abs
print(b)


print(len(b))

#append operation

b.append(90)
print(b)


#remove operation

b.remove(34)
print(b)


#slicing operation

print(b[7:])
print(b[:2])


#sort operation
b.sort()
print(b)

#reverse operation
b.reverse()
print(b)

